//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeCompanySoftware.GetData {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetData.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet GetDataSet(string strQry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dmlexecute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void Dmlexecute(string strQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertMasterRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet InsertMasterRecord(System.Data.DataSet pDataset, string strTransType, string[] strTableName, string strCondition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateMasterRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet UpdateMasterRecord(System.Data.DataSet pDataset, string[] strTableName, string strCondition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet DeleteRecord(string[] strTableName, string strCondition);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ServiceSoapChannel : ExchangeCompanySoftware.GetData.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<ExchangeCompanySoftware.GetData.ServiceSoap>, ExchangeCompanySoftware.GetData.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetDataSet(string strQry) {
            return base.Channel.GetDataSet(strQry);
        }
        
        public void Dmlexecute(string strQuery) {
            base.Channel.Dmlexecute(strQuery);
        }
        
        public System.Data.DataSet InsertMasterRecord(System.Data.DataSet pDataset, string strTransType, string[] strTableName, string strCondition) {
            return base.Channel.InsertMasterRecord(pDataset, strTransType, strTableName, strCondition);
        }
        
        public System.Data.DataSet UpdateMasterRecord(System.Data.DataSet pDataset, string[] strTableName, string strCondition) {
            return base.Channel.UpdateMasterRecord(pDataset, strTableName, strCondition);
        }
        
        public System.Data.DataSet DeleteRecord(string[] strTableName, string strCondition) {
            return base.Channel.DeleteRecord(strTableName, strCondition);
        }
    }
}
